### ISSUE TITLE
ftpd windows version , the ftp server will crash if input 'dir' 

### ISSUE THREAD

**Issue by simon1271** [wconrad/ftpd#44]
E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/disk_file_system.rb:311:i
n `gid_name': undefined method `name' for nil:NilClass (NoMethodError)
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/disk_file_sy
stem.rb:257:in `file_info'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/translate_ex
ceptions.rb:45:in `call'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/translate_ex
ceptions.rb:45:in `block (2 levels) in translate_exceptions'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/exception_tr
anslator.rb:24:in `translate_exceptions'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/translate_ex
ceptions.rb:44:in `block in translate_exceptions'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/file_system_
error_translator.rb:19:in `method_missing'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:4
04:in `block in format_list'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:4
03:in `map'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:4
03:in `format_list'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:3
99:in `list'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/cmd_list.rb:
12:in `block in cmd_list'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:3
14:in `close_data_server_socket_when_done'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/cmd_list.rb:
6:in `cmd_list'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/command_hand
lers.rb:41:in `execute'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:1
14:in `execute_command'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:5
1:in `block (2 levels) in run'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:4
1:in `loop'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:4
1:in `block in run'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:3
8:in `catch'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/session.rb:3
8:in `run'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/ftp_server.r
b:185:in `run_session'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/ftp_server.r
b:166:in `block in session'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/connection_t
racker.rb:36:in `track'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/ftp_server.r
b:165:in `session'
        from E:/Ruby22/lib/ruby/gems/2.2.0/gems/ftpd-2.0.0/lib/ftpd/server.rb:10
5:in `block in start_session_thread'

**Comment by wconrad** [comment]
Thank you for the bug report.  I have Windows now, so if I get a chance I'll set it up for Ruby development and see if ftpd can be made to work in Windows without too much trouble.

Windows support for ftpd is a low priority issue for me, behind other issues like getting the tests to pass in Ruby 2.4, so don't expect progress soon unless it comes from pull requests by others.
