### ISSUE TITLE
rake test:features seems to be broken

### ISSUE THREAD

**Issue by pcbeard** [wconrad/ftpd#50]
If I use Ruby 2.4.1 and install using rvm, I get this error message when trying to run tests with rake:

```
rvm use 2.4.1
gem install bundler
bundle install

rake test:features
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007fe8f6843ac8>
/Volumes/Users/beard/.rvm/gems/ruby-2.4.1/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:69:in `define'
/Volumes/Users/beard/.rvm/gems/ruby-2.4.1/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:61:in `initialize'
rake_tasks/yard.rake:4:in `new'
rake_tasks/yard.rake:4:in `<top (required)>'
/Volumes/Users/beard/Trees/ftpd/Rakefile:14:in `load'
/Volumes/Users/beard/Trees/ftpd/Rakefile:14:in `block in <top (required)>'
/Volumes/Users/beard/Trees/ftpd/Rakefile:14:in `each'
/Volumes/Users/beard/Trees/ftpd/Rakefile:14:in `<top (required)>'
/Volumes/Users/beard/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Volumes/Users/beard/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Volumes/Users/beard/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

I suspect it was the [change](https://github.com/wconrad/ftpd/commit/932e62ead1da7f957bca19571536e5fe2efcaaeb) that bumped rake to 12.0.0. Backing it out like this:

```
diff --git a/Gemfile b/Gemfile
index 42ffe63..d2a15b6 100644
--- a/Gemfile
+++ b/Gemfile
@@ -3,7 +3,7 @@ source 'http://rubygems.org'
 gem 'memoizer', '~> 1.0'
 
 group :test, :development do
-  gem 'rake', '~> 12.0'
+  gem 'rake', '~> 11.1'
 end
 
 group :test do
diff --git a/Gemfile.lock b/Gemfile.lock
index 75d8174..3a17115 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -62,7 +62,7 @@ GEM
     psych (2.2.4)
     public_suffix (2.0.5)
     rack (2.0.2)
-    rake (12.0.0)
+    rake (11.1.0)
     rdoc (5.1.0)
     redcarpet (3.4.0)
     rspec (3.6.0)
@@ -94,7 +94,7 @@ DEPENDENCIES
   double-bag-ftps (~> 0.1, >= 0.1.3)
   jeweler (~> 2.0)
   memoizer (~> 1.0)
-  rake (~> 12.0)
+  rake (~> 11.1)
   redcarpet (~> 3.1)
   rspec (~> 3.1)
   rspec-its (~> 1.0)
```

Then reinstalling rake like this:

```
gem uninstall rake
bundle install
```
Seems to restore testing functionality.

**Comment by wconrad** [comment]
Thanks.  I backed that change out.  The tests run in Ruby 2.3 now (but they're busted in 2.4, FYI.  FTPD should be fine with Ruby 2.4, but the tests require double-bag-ftps, which does not work with Ruby 2.4).

**Comment by wconrad** [comment]
The latest version of the gem uses rake 11.1 again.  The tests all pass on my box, and on travisci.  If they fail for you, will you please let me know?
